### ISSUE TITLE
IfyButton está disparando dois eventos quando especificado @click

### ISSUE THREAD

**Issue by lfpolli** [investfy/components#24]
O componente IfyButton está disparando dois eventos quando é especificado um listener utilizando @click.

Teste realizado:
```
      <IfyButton
        type="success"
        class="uppercase"
        size="lg"
        expanded
        @click="log($event)"
        >Log</IfyButton
      >
```

```
    log(event) {
      console.log(event)
    },
```
Após clicar no botão o output no console foi:
```
primeira chamada -> undefined 

segunda chamada -> resume.vue?1ebc:131 PointerEvent {isTrusted: true, pointerId: 1, width: 1, height: 1, pressure: 0, …}
```

Pode ser que esteja disparando o click do componente e o `native`

**Comment by vctrtvfrrr** [comment]
O problema do click duplicado parece ser causado por uma $emit duplo no componente:
https://github.com/investfy/components/blob/master/src/components/button/Button.vue#L20

**Comment by Gilson401** [comment]
A solução foi remover o  @click="$emit('click')" do botão interno do componente uma vez que  v-on="$listeners" já capta os eventos.
