### ISSUE TITLE
Ícone duplicado nos `Select`'s dentro de um componente `IfyTable`

### ISSUE THREAD

**Issue by vctrtvfrrr** [investfy/components#25]
Todo elemento `Select` dentro de um componente `IfyTable` aparece com os ícones de indicação de dropdown duplicados.

![Select](https://user-images.githubusercontent.com/1169416/162437689-cc418e77-003d-4cd0-bdca-f3af54363b94.png)

**Comment by Gilson401** [comment]
Não foi possível reproduzir este erro em ambiente dev. Posteriormente, conforme entendimento com a equipe, verificou-se que esta correção já estava pronta em dev. Não é necessário prosseguir com a issue.

**Comment by vctrtvfrrr** [comment]
Issue fechada por já estar resolvida em ambiente de produção.
